global:
    scrape_interval: 15s # Tăng lên để giảm tải cho hệ thống
    evaluation_interval: 15s # Đánh giá rules mỗi 15s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']

    - job_name: 'node_exporter'
      metrics_path: '/metrics'
      static_configs:
          - targets: ['node_exporter:9100']
 
    - job_name: 'cadvisor'
      static_configs:
          - targets: ['cadvisor:8080']
